Hexapod:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: L_front_leg_grp
    joint_model_group_pose: L_front_leg_pose_def
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - root_virtual_jnt
      - L_back_coxa_jnt
      - L_back_femur_jnt
      - L_back_tibia_jnt
      - L_front_coxa_jnt
      - L_front_femur_jnt
      - L_front_tibia_jnt
      - L_mid_coxa_jnt
      - L_mid_femur_jnt
      - L_mid_tibia_jnt
      - R_back_coxa_jnt
      - R_back_femur_jnt
      - R_back_tibia_jnt
      - R_front_coxa_jnt
      - R_front_femur_jnt
      - R_front_tibia_jnt
      - R_mid_coxa_jnt
      - R_mid_femur_jnt
      - R_mid_tibia_jnt
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # L_front_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_front_coxa_jnt
  #     - L_front_femur_jnt
  #     - L_front_tibia_jnt
  #   gains:
  #     L_front_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_front_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_front_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  # L_mid_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_mid_coxa_jnt
  #     - L_mid_femur_jnt
  #     - L_mid_tibia_jnt
  #   gains:
  #     L_mid_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_mid_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_mid_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  # L_back_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_back_coxa_jnt
  #     - L_back_femur_jnt
  #     - L_back_tibia_jnt
  #   gains:
  #     L_back_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_back_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_back_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #
  # L_front_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_front_coxa_jnt
  #     - L_front_femur_jnt
  #     - L_front_tibia_jnt
  #   gains:
  #     L_front_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_front_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_front_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  # L_mid_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_mid_coxa_jnt
  #     - L_mid_femur_jnt
  #     - L_mid_tibia_jnt
  #   gains:
  #     L_mid_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_mid_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_mid_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  # L_back_leg_grp_controller:
  #   type: effort_controllers/JointPositionController
  #   joints:
  #     - L_back_coxa_jnt
  #     - L_back_femur_jnt
  #     - L_back_tibia_jnt
  #   gains:
  #     L_back_coxa_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_back_femur_jnt: {p:100, d:1, i: 1, i_clamp: 1}
  #     L_back_tibia_jnt: {p:100, d:1, i: 1, i_clamp: 1}

  gazebo_ros_control/pid_gains:
    L_front_coxa_jnt: {p: 1, i: 0, d: 0}
    L_front_femur_jnt: {p: 1, i: 0, d: 0}
    L_front_tibia_jnt: {p: 1, i: 0, d: 0}
    L_mid_coxa_jnt: {p: 1, i: 0, d: 0}
    L_mid_femur_jnt: {p: 1, i: 0, d: 0}
    L_mid_tibia_jnt: {p: 1, i: 0, d: 0}
    L_back_coxa_jnt: {p: 1, i: 0, d: 0}
    L_back_femur_jnt: {p: 1, i: 0, d: 0}
    L_back_tibia_jnt: {p: 1, i: 0, d: 0}

    R_front_coxa_jnt: {p: 1, i: 0, d: 0}
    R_front_femur_jnt: {p: 1, i: 0, d: 0}
    R_front_tibia_jnt: {p: 1, i: 0, d: 0}
    R_mid_coxa_jnt: {p: 1, i: 0, d: 0}
    R_mid_femur_jnt: {p: 1, i: 0, d: 0}
    R_mid_tibia_jnt: {p: 1, i: 0, d: 0}
    R_back_coxa_jnt: {p: 1, i: 0, d: 0}
    R_back_femur_jnt: {p: 1, i: 0, d: 0}
    R_back_tibia_jnt: {p: 1, i: 0, d: 0}

  controller_list:
    - name: L_front_leg__controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - L_front_coxa_jnt
        - L_front_femur_jnt
        - L_front_tibia_jnt
    - name: L_mid_leg_grp_controller
      action_ns: follow_joint_trajectory
      default: False
      type: FollowJointTrajectory
      joints:
        - L_mid_coxa_jnt
        - L_mid_femur_jnt
        - L_mid_tibia_jnt
    - name: L_back_leg_grp_controller
      action_ns: follow_joint_trajectory
      default: False
      type: FollowJointTrajectory
      joints:
        - L_back_coxa_jnt
        - L_back_femur_jnt
        - L_back_tibia_jnt
    - name: R_front_leg_grp_controller
      action_ns: follow_joint_trajectory
      default: False
      type: FollowJointTrajectory
      joints:
        - R_front_coxa_jnt
        - R_front_femur_jnt
        - R_front_tibia_jnt
    - name: R_mid_leg_grp_controller
      action_ns: follow_joint_trajectory
      default: False
      type: FollowJointTrajectory
      joints:
        - R_mid_coxa_jnt
        - R_mid_femur_jnt
        - R_mid_tibia_jnt
    - name: R_back_leg_grp_controller
      action_ns: follow_joint_trajectory
      default: False
      type: FollowJointTrajectory
      joints:
        - R_back_coxa_jnt
        - R_back_femur_jnt
        - R_back_tibia_jnt
