FROM ubuntu:24.04 AS base

ARG LLVM_VERSION=21
ARG ROS_DISTRO=jazzy

ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y software-properties-common lsb-release ca-certificates gnupg wget curl

RUN apt-get update && apt-get install -y locales sudo bash \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

ENV add-apt-repository universe \
    && apt update \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-add-repository ppa:ubuntu-toolchain-r/test

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    bash-completion \
    autoconf \
    binutils \
    bison \
    build-essential \
    bzip2 \
    cmake \
    flex \
    gawk \
    git \
    git-lfs \
    gnupg2 \
    gzip \
    libgmp-dev \
    libisl-dev \
    libmpc-dev \
    libmpfr-dev \
    libtool \
    lsb-release \
    make \
    perl \
    python3 \
    python3-pip \
    tar \
    unzip \
    libzstd-dev \
    ca-certificates \
    lua5.3 \
    pkg-config \
    ninja-build \
    valgrind \
    gpg \
    software-properties-common \
    gdb \
    cppcheck \
    zip \
    default-jdk

FROM base AS tools

# Example using the download link for GCC 15.1.0
# You may need to adjust the version number if a newer one is available
# RUN wget https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.gz \
#     && tar -xzf gcc-15.1.0.tar.gz \
#     && cd gcc-15.1.0/ \
#     && mkdir build && cd build \
#     && ../configure --prefix=/usr/local/gcc-15.1.0 --disable-multilib --enable-languages=c,c++ \
#     && make -j $(nproc) \
#     && make install

# RUN update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-15.1.0/bin/gcc 1510 && \
#     update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-15.1.0/bin/g++ 1510

RUN wget https://apt.llvm.org/llvm.sh \
    && chmod +x llvm.sh \
    && ./llvm.sh ${LLVM_VERSION} all \
    && rm llvm.sh

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-as llvm-as /usr/bin/llvm-as-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-${LLVM_VERSION}  100 \
    && update-alternatives --install /usr/bin/llvm-readelf llvm-readelf /usr/bin/llvm-readelf-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-dwarfdump llvm-dwarfdump /usr/bin/llvm-dwarfdump-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-dlltool llvm-dlltool /usr/bin/llvm-dlltool-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-strings llvm-strings /usr/bin/llvm-strings-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-dwp llvm-dwp /bin/llvm-dwp-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/llvm-lto llvm-lto /bin/llvm-lto-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/clang-format clang-format /bin/clang-format-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/clang-tidy clang-tidy /bin/clang-tidy-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/clangd clangd /bin/clangd-${LLVM_VERSION} 100

RUN python3 -m pip install --no-cache-dir \
    argcomplete \
    pytest \
    pytest-cov \
    pre-commit \
    commitizen \
    flake8 \
    black \
    isort



FROM tools AS ros2
# Install ROS 2 Jazzy

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') \
    && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
    && apt-get install -y /tmp/ros2-apt-source.deb

RUN apt-get update && \
    apt-get install --no-install-recommends -y ros-jazzy-ros-base \
    python3-colcon-common-extensions

FROM ros2 AS devenv

ARG USERNAME=user
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

FROM devenv AS final

ENV SHELL /bin/bash
RUN echo "source /opt/ros/jazzy/setup.bash" >> /home/$USERNAME/.bashrc
CMD ["/bin/bash"]
